# Generated by Django 5.1.3 on 2026-06-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sephora_app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
