# Generated by Django 5.1.3 on 2026-06-22 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sephora_app', '0003_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sephora_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sephora_app.userregister')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
